version: '2'
services:
    mp__pinger:
        image: node:latest
        container_name: mp__pinger
        command: node /src/app/index.js
        volumes:
            - ./Pinger:/src/app
        ports:
            - "3000:3000"
        links:
            - mp__pinger_mongo:mongo
            - mp__redis:redis
    mp__pinger_mongo:
        image: mongo:3.4
        container_name: mp__pinger_mongo
        volumes:
            - ./Pinger/data:/data/db
    mp__redis:
        image: redis:latest
        container_name: mp__redis

    mp_notifier:
        build: ./Notifier
        container_name: mp_notifier
        volumes:
            - ./Notifier:/src/app
        links:
            - mp__redis:redis
